//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppQuaack
{
    using System;
    using System.Collections.Generic;
    
    public partial class follower
    {
        public int followid { get; set; }
        public int subject { get; set; }
        public int follower1 { get; set; }
        public bool blocked { get; set; }
        public bool requestpending { get; set; }
    
        public virtual profile profile { get; set; }
        public virtual profile profile1 { get; set; }
    }
}
