//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppQuaack
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public message()
        {
            this.message11 = new HashSet<message>();
        }
    
        public int messid { get; set; }
        public System.DateTime messdatetime { get; set; }
        public int sender { get; set; }
        public Nullable<int> parentmessid { get; set; }
        public string message1 { get; set; }
        public bool removed { get; set; }
        public Nullable<int> removedby { get; set; }
    
        public virtual ICollection<message> message11 { get; set; }
        public virtual message message2 { get; set; }
        public virtual profile profile { get; set; }
        public virtual profile profile1 { get; set; }
    }
}
