//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppQuaack
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public profile()
        {
            this.follower = new HashSet<follower>();
            this.follower1 = new HashSet<follower>();
            this.message = new HashSet<message>();
            this.message1 = new HashSet<message>();
        }
    
        public int profileid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string profile1 { get; set; }
        public string email { get; set; }
        public string avatarlocation { get; set; }
        public string mobilenumber { get; set; }
        public bool verificationpending { get; set; }
        public Nullable<System.DateTime> verficationpendingdatetime { get; set; }
        public bool tempblocked { get; set; }
        public Nullable<System.DateTime> tempblockeddatetime { get; set; }
        public bool permblocked { get; set; }
        public Nullable<System.DateTime> permblockeddatetime { get; set; }
        public bool removed { get; set; }
        public Nullable<System.DateTime> removeddatetime { get; set; }
    
        public virtual ICollection<follower> follower { get; set; }
        public virtual ICollection<follower> follower1 { get; set; }
        public virtual ICollection<message> message { get; set; }
        public virtual ICollection<message> message1 { get; set; }
    }
}
